version: '2'
services:
    cloudreact-app:
        image: cloudreact
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cloudreact-mysql:3306/cloudreact?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cloudreact-mysql:
        extends:
            file: mysql.yml
            service: cloudreact-mysql
